# Generated by Django 5.2.7 on 2025-11-03 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='entrega',
            options={},
        ),
        migrations.AlterModelOptions(
            name='entregador',
            options={'verbose_name_plural': 'Entregadores'},
        ),
        migrations.AlterModelOptions(
            name='pagamento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='criado_em',
            new_name='data_cadastro',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='criado_em',
            new_name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='produtos',
        ),
        migrations.RemoveField(
            model_name='entregador',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='entregador',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='atualizado_em',
        ),
        migrations.AlterField(
            model_name='entrega',
            name='data_entrega_prevista',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='EntregaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrega_produtos', to='core.entrega')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrega_produtos', to='core.produto')),
            ],
            options={
                'unique_together': {('entrega', 'produto')},
            },
        ),
    ]
