# Generated by Django 5.2.7 on 2025-11-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cliente_options_alter_entrega_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregador',
            name='disponivel',
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='metodo',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão'), ('PIX', 'PIX'), ('BOLETO', 'Boleto'), ('FIADO', 'Fiado')], max_length=20),
        ),
    ]
